// Generated by scripts/prepare-images.mjs — do not edit by hand.
#pragma once
#include <pebble.h>

#define TRAIN_COUNT 10
// Sky strip baked above the train body, in source (canvas) pixels — used to place
// the type label in the gap above the train.
#define TRAIN_SKY_ABOVE 14

static const uint32_t TRAIN_RESOURCE_IDS[TRAIN_COUNT] = {
  RESOURCE_ID_TRAIN_DM90_2,
  RESOURCE_ID_TRAIN_WINK_2_ARRIVA,
  RESOURCE_ID_TRAIN_SGMM_2,
  RESOURCE_ID_TRAIN_SNG_3,
  RESOURCE_ID_TRAIN_SLT_4,
  RESOURCE_ID_TRAIN_GTW_6_ARRIVA,
  RESOURCE_ID_TRAIN_ICM_3,
  RESOURCE_ID_TRAIN_DDZ_4,
  RESOURCE_ID_TRAIN_VIRM_4,
  RESOURCE_ID_TRAIN_ICNG_5,
};

static const char *const TRAIN_NAMES[TRAIN_COUNT] = {
  "BUFFEL",
  "WINK",
  "SPRINTER (PLAN Y)",
  "SPRINTER (NIEUWE GENERATIE)",
  "SPRINTER (LIGHTTRAIN)",
  "STADLER GTW",
  "KOPLOPER",
  "DUBBELDEKKER",
  "REGIORUNNER",
  "INTERCITY NIEUWE GENERATIE",
};

// Per-train upward nudge for the label (source px), for tall-cab trains.
static const int TRAIN_LABEL_DY[TRAIN_COUNT] = {
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  0,
  0,
  0,
};
